### PR TITLE
fixes #409: Adds support for compacted topics and commit offset resetting

### LINKED ISSUE #409: Parallel Consumer keeps committing the old offset after OFFSET_OUT_OF_RANGE in auto.offset.reset = latest
Hi @astubbs, 
Thanks for this great library. Recently, I have been consistently seeing the consumer lag on some partitions of the topic when offset become out of range for that partition. This happens even with latest PC version - 0.5.2.2. I'm using KEY ordering.

This might be related to #352. Sample logs below.

- Last committed offset is 86321 and it's no longer available on broker due to retention policy.
- And it gets reset to latest offset - 88617

`12-09-2022 11:48:42.904 TraceId/SpanId: / [pc-broker-poll] INFO  org.apache.kafka.clients.consumer.internals.Fetcher.handleOffsetOutOfRange - [Consumer clientId=my-topic-consumer-client, groupId=my-topic-consumer] Fetch position FetchPosition{offset=86321, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[localhost:6668 (id: 1 rack: null)], epoch=596}} is out of range for partition my-topic-4, resetting offset
12-09-2022 11:48:43.148 TraceId/SpanId: / [pc-broker-poll] INFO  org.apache.kafka.clients.consumer.internals.SubscriptionState.maybeSeekUnvalidated - [Consumer clientId=my-topic-consumer-client, groupId=my-topic-consumer] Resetting offset for partition my-topic-4 to position FetchPosition{offset=88617, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[localhost:6668 (id: 1 rack: null)], epoch=596}}.
..`

New message at offset 88618 get consumed by the consumer

`12-09-2022 11:49:32.550 TraceId/SpanId: c65c59c9b8c75d88/b26a1c4eea95894d [pc-pool-3-thread-1] INFO  my.test.kafka.consumer.MyConsumer.consume - event=PROCESSING_COMPLETED, Event details: [id=cfd1d7e0-324d-11ed-8e3e-99871a3f782d, name=Event started, partition=4, offset=88618]
12-09-2022 11:49:32.550 TraceId/SpanId: a49e9995c6147711/d466506b2f29b224 [pc-pool-3-thread-1] INFO  my.test.kafka.consumer.MyConsumer.consume - event=PROCESSING_COMPLETED, Event details: [id=cbabd4e0-324d-11ed-8e3e-99871a3f782d, name=Event completed, partition=4, offset=88617]
12-09-2022 11:49:32.781 TraceId/SpanId: c2a3cfd96ea76036/37104cfb0345e5b1 [pc-pool-3-thread-3] INFO  my.test.kafka.consumer.MyConsumer.consume - event=PROCESSING_COMPLETED, Event details: [id=cff676e0-324d-11ed-8e3e-99871a3f782d, name=Other event created, partition=4, offset=88619]
..`

But, old offset 86321 was being repeatedly committed. Hence, the consumer lag happens and it's continuously growing.

`12-09-2022 11:49:35.552 TraceId/SpanId: / [pc-broker-poll] DEBUG io.confluent.parallelconsumer.internal.AbstractOffsetCommitter.retrieveOffsetsAndCommit - Commit starting - find completed work to commit offsets
12-09-2022 11:49:35.552 TraceId/SpanId: / [pc-broker-poll] DEBUG io.confluent.parallelconsumer.internal.AbstractOffsetCommitter.retrieveOffsetsAndCommit - Will commit offsets for 5 partition(s): {my-topic-4=OffsetAndMetadata{offset=86321, leaderEpoch=null, metadata='bgAKAAMACgACAAsBDgACB8Y='}, my-topic-3=OffsetAndMetadata{offset=89148, leaderEpoch=null, metadata='bAAJfgEA'}, my-topic-2=OffsetAndMetadata{offset=88725, leaderEpoch=null, metadata='bAATPIAGAA=='}, my-topic-1=OffsetAndMetadata{offset=107886, leaderEpoch=null, metadata='bAAGIAA='}, my-topic-0=OffsetAndMetadata{offset=89200, leaderEpoch=null, metadata='bgALAAE='}}
12-09-2022 11:49:35.552 TraceId/SpanId: / [pc-broker-poll] DEBUG io.confluent.parallelconsumer.internal.AbstractOffsetCommitter.retrieveOffsetsAndCommit - Begin commit
..`

- Is it possible that PC is not aware of "auto.offset.reset=latest" event and highest committable offset somehow remains 86321 and that's why it gets committed with every commit loop? 
- Is it possible for PC to be able to recover from this situation just like normal consumer does and be aware of "auto.offset.reset=latest" and commit the offsets of new messages as it consumes, avoiding consumer lag.
- Under normal circumstances, are there any possible exceptional scenarios where we can run into consumer lag and PC is not able to recover from it hence the lag continue to grow? E.g. what happens if it somehow failed to commit an offset, how can PC recover from this without restarting the consumer?

### PR DESCRIPTION
**Pull request by astubbs**
* fixes #409: Adds support for compacted topics and commit offset resetting (#425)
** Truncate the offset state when bootstrap polled offset higher or lower than committed
** Prune missing records from the tracked incomplete offset state, when they're missing from polled batches

Fixes:
- #409 

### Checklist

- [x] Changelog

### CODE REVIEW

File: parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetMapCodecManager.java [hunk 1]
```diff
@@ -72,6 +72,7 @@ public static class HighestOffsetAndIncompletes {
         /**
          * Of the offsets encoded, the incomplete ones.
          */
+        // todo change to List as Sets have no order
```
Comment (astubbs) [inline parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetMapCodecManager.java:75]: change set to list

File: parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionState.java [hunk 2]
```diff
@@ -59,7 +56,12 @@
      * so that the broker polling thread can grab it, if it wants to commit - i.e. the poller would not prepare/query
      * the data for itself. See also #200 Refactor: Consider a shared nothing architecture.
      */
-    private final ConcurrentSkipListSet<Long> incompleteOffsets;
+    private ConcurrentSkipListSet<Long> incompleteOffsets;
+
+    /**
+     * Marker for the first record to be tracked. Used for some initial analysis.
+     */
+    private boolean noWorkAddedYet = true;
```
Comment (astubbs) [inline parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionState.java:64]: remove?

File: parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionState.java [hunk 3]
```diff
@@ -199,11 +202,43 @@ private void updateHighestSucceededOffsetSoFar(WorkContainer<K, V> work) {
 
     public void addWorkContainer(WorkContainer<K, V> wc) {
         long newOffset = wc.offset();
+
+//        if (noWorkAddedYet) {
```
Comment (astubbs) [inline parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/PartitionState.java:206]: clean

File: parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/PartitionStateTest.java [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+
+class PartitionStateTest {
+
+    ModelUtils mu = new ModelUtils(new PCModuleTestEnv());
+
+    /**
+     * @see PartitionState#maybeTruncateBelow
+     */
+    @Test
+    void bootstrapTruncation() {
```
Comment (astubbs) [inline parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/PartitionStateTest.java:27]: off by one tests

**Review by astubbs — COMMENTED** [review]
....

**Comment by astubbs** [comment]
This needs some more careful thinking through, the solution proposed won't work. I thought it needed to be checked continuously, but actually it may indeed only be upon first initial poll - as it's only the committed offset that's affected, not the offset map - I think.

**Comment by astubbs** [comment]
> This needs some more careful thinking through, the solution proposed won't work. I thought it needed to be checked continuously, but actually it may indeed only be upon first initial poll - as it's only the committed offset that's affected, not the offset map - I think.

done.

File: parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/state/PartitionStateCommittedOffsetIT.java [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+
+/*-
+ * Copyright (C) 2020-2022 Confluent, Inc.
+ */
+
+import io.confluent.parallelconsumer.integrationTests.BrokerIntegrationTest;
+import org.apache.kafka.clients.admin.AdminClient;
+import org.apache.kafka.common.TopicPartition;
+
+class PartitionStateCommittedOffsetIT extends BrokerIntegrationTest<String, String> {
```
Comment (astubbs) [inline parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/state/PartitionStateCommittedOffsetIT.java:11]: implement

File: parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/PartitionStateCommittedOffsetTest.java [hunk 6]
```diff
@@ -0,0 +1,176 @@
...
+                state.addNewIncompleteWorkContainer(wc);
+            }
+        }
+    }
+//
+//    /**
+//     *
+//     */
+//    @Test
+//    void bootstrapPollOffsetHigherViaManualCGRset() {
```
Comment (astubbs) [inline parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/state/PartitionStateCommittedOffsetTest.java:129]: delete?

**Review by astubbs — COMMENTED** [review]
...

File: parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/state/PartitionStateCommittedOffsetIT.java [hunk 7]
```diff
@@ -0,0 +1,524 @@
...
+        groupId = getKcu().getConsumer().groupMetadata().groupId();
+        this.ac = getKcu().getAdmin();
+    }
+
+    /**
+     * Test for offset gaps in partition data (i.e. compacted topics)
+     */
+    @Test
+    void compactedTopic() {
+        KafkaContainer compactingBroker = setupCompactingKafkaBroker();
```
Comment (astubbs) [inline parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/state/PartitionStateCommittedOffsetIT.java:92]: compacting broker seems to have introduced a lot of timeout errors:

11:26:10  26:10.195  WARN  [kafka-producer-network-thread | producer-164]  (NetworkClient.java:775)#processDisconnection [Producer clientId=producer-164] Connection to node 1 (/172.31.15.245:34928) could not be established. Broker may not be available.

Might be connected to having multiple brokers running and KCU not closing cleanly to a broker that's gone?

Comment (astubbs) [reply parallel-consumer-core/src/test-integration/java/io/confluent/parallelconsumer/integrationTests/state/PartitionStateCommittedOffsetIT.java]: fixed with tighter resource management and locking down kcu access

**Review by astubbs — COMMENTED** [review]
lgtm
