### PR TITLE
Final improvements before releasing 3.0

### LINKED ISSUE #52: Bug in run length encoder - doesn't work with offset gap in source partition
For example, in compacted topics the offsets are not strictly sequential - there can be gaps. This was over looked with the RunLength encoder.

### PR DESCRIPTION
**Pull request by astubbs**
Fixes #52

### CODE REVIEW

File: parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelConsumerOptions.java [hunk 1]
```diff
@@ -67,34 +69,42 @@
...
+         * #PERIODIC_TRANSACTIONAL_PRODUCER}. Slower but potentially less duplicates than {@link
+         * #PERIODIC_CONSUMER_ASYNCHRONOUS} upon replay.
          */
-        CONSUMER_SYNC,
+        PERIODIC_CONSUMER_SYNC,
+
         /**
-         * Fastest option, under normal conditions will have few of no duplicates. Under failure revocery may have more
-         * duplicates than {@link #CONSUMER_SYNC}.
+         * Periodically commits offsets asynchronously. The fastest option, under normal conditions will have few of no duplicates. Under failure recovery may have more
```
Comment (JorgenRingen) [inline parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ParallelConsumerOptions.java:90]: "of no" -> "or no"
