### PR TITLE
PL-354 - fix key equality

### LINKED ISSUE #579: ByteArray key parallelism is not working as expected
When used ByteArray as key in kafka, splitting work by ProcessingOrder.KEY is not working well.
I think because of Lomboks @EqualsAndHashCode, which is not able to infer key type and compare arrays.

I am using ByteArrayDeserializer in my kafka consumer.

image

```@Test
    void testEqualsKey() {
        assertNotEquals(
                new KeyOrderedKey(new TopicPartition("1", 1), "1".getBytes()),
                new KeyOrderedKey(new TopicPartition("1", 1), "1".getBytes())
        );
        assertEquals(
                new KeyOrderedKey(new TopicPartition("1", 1), "1"),
                new KeyOrderedKey(new TopicPartition("1", 1), "1")
        );
    }

### PR DESCRIPTION
**Pull request by rkolesnev**
Fixed key equality comparison - use deep equality / hash code for Object and primitive arrays.
Resolves #579 
### Checklist

- [ ] Documentation (if applicable)
- [X] Changelog

### CODE REVIEW

**Review by eddyv — COMMENTED** [review]
The changes look fine... but the pipeline is complaining that it's slow. Maybe the comparisons are too slow?

File: parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/ShardKey.java [hunk 1]
```diff
@@ -100,10 +99,13 @@ public int hashCode() {
             }
             if (isArray(key)) {
                 result = result + arrayHashCode(key);
+            } else {
+                result = result + key.hashCode();
```
Comment (eddyv) [inline parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/state/ShardKey.java:103]: 😮 👍

**Review by eddyv — APPROVED** [review]
