### PR TITLE
Dynamic work loading, self tuning, better back pressure, better performance

### LINKED ISSUE #38: Back pressure system broken - max uncommitted message settings not honoured
Causes #35

### PR DESCRIPTION
**Pull request by astubbs**
Self tuning, faster 
Fixes #38

### CODE REVIEW

File: parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ExponentialMovingAverage.java [hunk 1]
```diff
@@ -0,0 +1,21 @@
+package io.confluent.parallelconsumer;
```
Comment (astubbs) [inline parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/ExponentialMovingAverage.java:1]: delete

File: parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/BackoffAnalyser.java [hunk 2]
```diff
@@ -0,0 +1,46 @@
+package io.confluent.parallelconsumer;
```
Comment (astubbs) [inline parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/BackoffAnalyser.java:1]: delete

File: README.adoc [hunk 3]
```diff
@@ -381,7 +381,7 @@ Where `${project.version}` is the version to be used:
         var options = ParallelConsumerOptions.<String, String>builder()
                 .ordering(KEY) // <2>
                 .maxMessagesToQueue(1000) // <3>
```
Comment (astubbs) [inline README.adoc:383]: check docs

File: parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/WindowedEventRate.java [hunk 4]
```diff
@@ -0,0 +1,30 @@
+package io.confluent.parallelconsumer;
```
Comment (astubbs) [inline parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/WindowedEventRate.java:1]: delete
