### PR TITLE
Fixes #547 - Cleanup WorkManager#numberRecordsOutForProcessing when w…

### LINKED ISSUE #547: Parallel consumer doesn't process any more records due to incorrect management of work
Parallel Consumer threads pauses polling messages from topic/partitions(s) and hence doesn't invoke user function, due to the "leak" in the counter of non-existent work when partition state changes. (Rebalancing, offline etc).

Confluent library version: 0.5.2.4

Possible (Observed) root cause - 
The problem appears to be stemming from not cleaning up the variable `WorkManager.java#numberRecordsOutForProcessing`, when the partition is revoked (partition epoch changes). The effect is gradual, until the numberOfRecordsOutForProcessing hits the Max value formulated via `ParallelConsumerOptions`.

Due to the above,  the consumer  stops polling/processing messages which causes consumer lag to build up.

Temporary Work Around: Restarting the process.

PC-Options

[thread_stack_pc.txt](https://github.com/confluentinc/parallel-consumer/files/10727790/thread_stack_pc.txt)

### PR DESCRIPTION
**Pull request by RaviKalasapur**
…ork is stale

Description...

### Checklist

- [x] Documentation (if applicable)
- [x] Changelog

### CODE REVIEW

File: parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/internal/PCModuleTestEnv.java [hunk 1]
```diff
@@ -23,6 +26,23 @@
...
+        return limitedDynamicLoadFactor;
+    }
+
+    public PCModuleTestEnv(final ParallelConsumerOptions<String, String> optionsInstance,
+                           final boolean transactionalProducer,
+                           final CountDownLatch latch) {
+        super(optionsInstance);
+        this.transactionalProducer = transactionalProducer;
+        this.workManagerController = Optional.of(latch);
+    }
```
Comment (rkolesnev) [inline parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/internal/PCModuleTestEnv.java:45]: remove the transactionalProducer flag and corresponding code that was added - in test itself instead only set producer on CommitMode.PERIODIC_TRANSACTIONAL_PRODUCER. 
For the new test - Producer is only needed for the Transactional mode and therefore its enough to not set the producer for other modes rather than create non-transactional producer.

File: parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSSStreamProcessorRebalancedTest.java [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+
+    private ParallelConsumerOptions<String, String> getBaseOptions(final CommitMode commitMode) {
+        return ParallelConsumerOptions.<String, String>builder()
+                .commitMode(commitMode)
+                .producer(producerSpy)
+                .consumer(consumerSpy)
+                .batchSize(2)
+                .maxConcurrency(1)
+                .build();
+    }
```
Comment (rkolesnev) [inline parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSSStreamProcessorRebalancedTest.java:82]: only set producer when using CommitMode.PERIODIC_TRANSACTIONAL_PRODUCER - this way changes to the PCModuleTestEnv and minimized.
```suggestion
       ParallelConsumerOptions.ParallelConsumerOptionsBuilder<String, String> optionsBuilder =
                ParallelConsumerOptions.<String, String>builder()
                        .commitMode(commitMode)
                        .consumer(consumerSpy)
                        .batchSize(2)
                        .maxConcurrency(1);
        if (commitMode == CommitMode.PERIODIC_TRANSACTIONAL_PRODUCER) {
            optionsBuilder.producer(producerSpy);
        }
        return optionsBuilder.build();
    }
```

**Review by rkolesnev — CHANGES_REQUESTED** [review]

File: README.adoc [hunk 3]
```diff
@@ -1318,6 +1318,7 @@ endif::[]
 
 * fixes: #195 NoSuchFieldException when using consumer inherited from KafkaConsumer (#469)
 * fix: After new performance fix PR#530 merges - corner case could cause out of order processing (#534)
+* fix: #547 - Cleanup WorkManager's Count of In-Progress work, when work is stale
```
[the remark this answers is not in the document]
Comment (RaviKalasapur) [reply README.adoc]: Got it, Thanks  👍

File: CHANGELOG.adoc [hunk 4]
```diff
@@ -20,6 +20,7 @@ endif::[]
 
 * fixes: #195 NoSuchFieldException when using consumer inherited from KafkaConsumer (#469)
 * fix: After new performance fix PR#530 merges - corner case could cause out of order processing (#534)
+* fix: #547 - Cleanup WorkManager's Count of In-Progress work, when work is stale
```
[the remark this answers is not in the document]
Comment (RaviKalasapur) [reply CHANGELOG.adoc]: Fixed.

File: parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java [hunk 5]
```diff
@@ -1196,10 +1186,60 @@ protected <R> List<ParallelConsumer.Tuple<ConsumerRecord<K, V>, R>> runUserFunct
...
+     */
+    protected void handleStaleWork(final List<WorkContainer<K, V>> workContainerBatch) {
+        final List<WorkContainer<K, V>> staleWorkContainers = workContainerBatch
+                .stream()
+                .filter(wm::checkIfWorkIsStale)
+                .collect(Collectors.toList());
+        final PollContextInternal<K, V> internalContext = new PollContextInternal<>(staleWorkContainers);
+        try {
+            // when epoch's change, we can't remove them from the executor pool queue, so we just have to skip them when we find them
+            log.debug("Pool found work from old generation of assigned work, skipping message as epoch doesn't match current {}", workContainerBatch);
```
[the remark this answers is not in the document]
Comment (RaviKalasapur) [reply parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/internal/AbstractParallelEoSStreamProcessor.java]: oops.

File: parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/internal/PCModuleTestEnv.java (hunk 1 above)
Comment (RaviKalasapur) [reply parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/internal/PCModuleTestEnv.java]: Done, makes it lot simpler 👍

File: parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSSStreamProcessorRebalancedTest.java (hunk 2 above)
Comment (RaviKalasapur) [reply parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/ParallelEoSSStreamProcessorRebalancedTest.java]: Done.

**Review by rkolesnev — APPROVED** [review]
LGTM
