### PR TITLE
fixes #327: Improve error message when Kafka Streams magic number found

### LINKED ISSUE #327: When unexpected magic bytes occur, improve the feedback in the error shown to the user
was: Friendlier error when offset decoding fails

When unexpected magic bytes occur, improve the feedback in the error shown to the user.

This can happen when PC is used on a topic, in a CG which had committed something to the metadata which is unexpected. A very rare case, but easy to catch and produce a meaningful error.

Prompted from https://github.com/confluentinc/parallel-consumer/issues/326

- [ ] On magic byte error, log full metadata
- [ ] Common error could be CG reused from KS app - detect KS magic byte and advice as such ([inspiration from comment](https://github.com/confluentinc/parallel-consumer/issues/326#issuecomment-1173777888) #326 )

### PR DESCRIPTION
**Pull request by nachomdo**
Fixes: https://github.com/confluentinc/parallel-consumer/issues/327

```
36:31.314 INFO  [pc-broker-poll]  (AbstractParallelEoSStreamProcessor.java:387#onPartitionsAssigned) Assigned 3 total (3 new) partition(s) [input-topic-0, input-topic-1, input-topic-2]
36:31.343 ERROR [pc-broker-poll]  (PartitionStateManager.java:116#onPartitionsAssigned) Error in onPartitionsAssigned
io.confluent.parallelconsumer.offsets.KafkaStreamsV2EncodingNotSupported: Kafka Streams offset metadata V2 not supported
	at io.confluent.parallelconsumer.offsets.EncodedOffsetPair.getDecodedIncompletes(EncodedOffsetPair.java:120) ~[classes/:na]
	at io.confluent.parallelconsumer.offsets.OffsetMapCodecManager.decodeCompressedOffsets(OffsetMapCodecManager.java:246) ~[classes/:na]
	at io.confluent.parallelconsumer.offsets.OffsetMapCodecManager.deserialiseIncompleteOffsetMapFromBase64(OffsetMapCodecManager.java:168) ~[classes/:na]
	at io.confluent.parallelconsumer.offsets.OffsetMapCodecManager.deserialiseIncompleteOffsetMapFromBase64(OffsetMapCodecManager.java:158) ~[classes/:na]
	at io.confluent.parallelconsumer.offsets.OffsetMapCodecManager.decodePartitionState(OffsetMapCodecManager.java:172) ~[classes/:na]
	at io.confluent.parallelconsumer.offsets.OffsetMapCodecManager.lambda$loadPartitionStateForAssignment$0(OffsetMapCodecManager.java:133) ~[classes/:na]
	at java.base/java.util.HashMap.forEach(HashMap.java:1421) ~[na:an]

```
### Checklist

- [] Documentation (if applicable)
- [] Changelog

### CODE REVIEW

**Review by astubbs — CHANGES_REQUESTED** [review]
Good work! 

We only need one exception - if that's the pattern to use
can you include a reference for where you got the magic number info from? byte 1 and 2

if this is the error that's printed:
"Kafka Streams offset metadata V1 not supported"
we need something more friendly. should be something like "it looks like you're reusing a kafka streams consumer group id with PC. This isn't supported - you should use a fresh consumer group, unique to your use of pc" - something like that?

File: parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/offsets/WorkManagerOffsetMapCodecManagerTest.java [hunk 1]
```diff
@@ -359,6 +360,45 @@ void deserialiseBitSet() {
         assertThat(deserialisedBitSet).isEqualTo(input);
     }
 
+    @SneakyThrows
```
Comment (astubbs) [inline parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/offsets/WorkManagerOffsetMapCodecManagerTest.java:363]:
```suggestion
/**
* Tests for friendly errors when Kafka Streams (as far as we can guess) magic numbers are found in the offset metadata.
*/
    @SneakyThrows
```

File: parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/offsets/WorkManagerOffsetMapCodecManagerTest.java [hunk 2]
```diff
@@ -359,6 +360,45 @@ void deserialiseBitSet() {
...
+        // timestamp
+        input.putLong(System.currentTimeMillis());
+
+        EncodedOffsetPair encodedOffsetPair = EncodedOffsetPair.unwrap(input.array());
+        assertThatThrownBy(()->encodedOffsetPair.getDecodedIncompletes(0L))
+                .isInstanceOf(KafkaStreamsEncodingNotSupported.class)
+                .hasMessage("It looks like you're reusing a Kafka Streams consumer group id. This isn't supported. Please, use a fresh consumer group, unique to PC");
+    }
+
+    @SneakyThrows
```
Comment (astubbs) [inline parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/offsets/WorkManagerOffsetMapCodecManagerTest.java:378]: javadoc as above or similar

File: parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetEncoding.java [hunk 3]
```diff
@@ -39,7 +39,15 @@ public enum OffsetEncoding {
      * switch from encoding run lengths as Shorts to Integers
      */
     RunLengthV2(v2, (byte) 'e'),
-    RunLengthV2Compressed(v2, (byte) 'p');
+    RunLengthV2Compressed(v2, (byte) 'p'),
+
+    /**
+     * checks for pre-existing Kafka Streams metadata
+     * https://github.com/apache/kafka/blob/cc77a38d280657a0e3969b255f103af4d11c7914/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopicPartitionMetadata.java#L33
```
Comment (astubbs) [inline parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetEncoding.java:46]: good hunting!
```suggestion
     * <a href="https://github.com/apache/kafka/blob/cc77a38d280657a0e3969b255f103af4d11c7914/streams/src/main/java/org/apache/kafka/streams/processor/internals/TopicPartitionMetadata.java#L33">source from Kafka Streams code</a>
```

or something like that

File: parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetEncoding.java [hunk 4]
```diff
@@ -39,7 +39,15 @@ public enum OffsetEncoding {
      * switch from encoding run lengths as Shorts to Integers
      */
     RunLengthV2(v2, (byte) 'e'),
-    RunLengthV2Compressed(v2, (byte) 'p');
+    RunLengthV2Compressed(v2, (byte) 'p'),
+
+    /**
+     * checks for pre-existing Kafka Streams metadata
```
Comment (astubbs) [inline parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetEncoding.java:45]:
```suggestion
     * Checks for pre-existing Kafka Streams metadata. Although the Kafka Streams magic numbers are annoyingly simple, ours are not, so should be safe to take this guess that they are indeed from Kafka Streams.
```

File: parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/offsets/WorkManagerOffsetMapCodecManagerTest.java [hunk 5]
```diff
@@ -359,6 +360,45 @@ void deserialiseBitSet() {
...
+        final var input = ByteBuffer.allocate(32);
+        // magic number
+        input.put((byte) 1);
+        // timestamp
+        input.putLong(System.currentTimeMillis());
+
+        EncodedOffsetPair encodedOffsetPair = EncodedOffsetPair.unwrap(input.array());
+        assertThatThrownBy(()->encodedOffsetPair.getDecodedIncompletes(0L))
+                .isInstanceOf(KafkaStreamsEncodingNotSupported.class)
+                .hasMessage("It looks like you're reusing a Kafka Streams consumer group id. This isn't supported. Please, use a fresh consumer group, unique to PC");
```
Comment (astubbs) [inline parallel-consumer-core/src/test/java/io/confluent/parallelconsumer/offsets/WorkManagerOffsetMapCodecManagerTest.java:375]: just check for keys words in the message, not the whole sentence. makes the test less brittle.

File: parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/EncodedOffsetPair.java [hunk 6]
```diff
@@ -114,6 +114,9 @@ public HighestOffsetAndIncompletes getDecodedIncompletes(long baseOffset) {
             case BitSetV2Compressed -> deserialiseBitSetWrapToIncompletes(BitSetV2, baseOffset, decompressZstd(data));
             case RunLengthV2 -> runLengthDecodeToIncompletes(encoding, baseOffset, data);
             case RunLengthV2Compressed -> runLengthDecodeToIncompletes(RunLengthV2, baseOffset, decompressZstd(data));
+            case KafkaStreams, KafkaStreamsV2 ->
+                    throw new KafkaStreamsEncodingNotSupported(
+                            "It looks like you're reusing a Kafka Streams consumer group id. This isn't supported. Please, use a fresh consumer group, unique to PC");
```
Comment (astubbs) [inline parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/EncodedOffsetPair.java:119]: move the message into the exception as a constant? seeing as there are no other uses of the exception, I think that would make it more understandable.
Also,
```suggestion
                            "It looks like you might be reusing a Kafka Streams consumer group id, as KS magic numbers were found in the serialised payload, instead of our own. Using PC on top of KS commit data isn't supported. Please, use a fresh consumer group, unique to PC.");
```

File: parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetEncoding.java (hunk 3 above)
Comment (astubbs) [reply parallel-consumer-core/src/main/java/io/confluent/parallelconsumer/offsets/OffsetEncoding.java:46]: actually as this is repeated, I would actually prefer to just refer to the documentation in the dedicated exception in KafkaStreamsEncodingNotSupported

```suggestion
     * @see KafkaStreamsEncodingNotSupported
     * ```

**Review by astubbs — CHANGES_REQUESTED** [review]
just about there! can close this one up quick now.

**Comment by nachomdo** [comment]
@astubbs Thanks for the review! I will apply the suggested feedback today so we can close this 😊

**Review by astubbs — APPROVED** [review]
